blank_issues_enabled: true
pull_request_templates:
  - name: 🧹 Chore / DevOps
    path: PULL_REQUEST_TEMPLATE/chore.md
  - name: 🧪 Testing
    path: PULL_REQUEST_TEMPLATE/testing.md
  - name: 📦 Default
    path: PULL_REQUEST_TEMPLATE/default.md